
# .pre-commit-config.yaml
# Pre-commit hooks configuration for YAML validation

repos:
  # Local custom hooks for specific validation
  - repo: local
    hooks:
      # YAML Encryption Check - Only for secret folder
      - id: yaml-encryption-check
        name: Check YAML Encryption
        description: Ensures all YAML files which mach __*.yaml are encrypted
        entry: .pre-commit-hooks/check-yaml-encryption.sh
        language: script
        files: ^secret/.*\.(yaml|yml)$
        pass_filenames: true
        stages: [commit]
        verbose: true